// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qslqdlnlttngdjgsffvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzbHFkbG5sdHRuZ2RqZ3NmZnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzI2NTAsImV4cCI6MjA1ODg0ODY1MH0.G2ICsK03qSqD-EdilWxJvjj2HXsM4Bl8lDhdqsgfayU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);